server {
    listen 80;
    root /usr/share/nginx/html;
    index embed.html;
    location / {
        try_files $uri $uri/ /embed.html?$args;
    }
    location /sommelier-widget.js {
        try_files /sommelier-widget.js =404;
    }
}
